# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: Hello world
email: your-email@domain.com

description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  es: Escribir una gran descripción de su nueva página web aquí. Puede cambiar esta línea en _config.yml. Aparecerá en la descripción meta tag (para los resultados en Google) y el cable RSS feed.xml.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

index:
  en:
  es: index.es.html

collections:
  posts:
    output: true
    permalink: /blog/:title/


exclude:
  - Gemfile
  - Gemfile.lock
